# Group Time

## time [/time]

### Create Time [POST]

+ project_id (number,required)
+ list_id (number,required)
+ task_id (number,required)

+ Request 
    + Body

            {
                "project_id": 7,
                "list_id": 168,
                "task_id": 207,
            }

+ Response 200 (application/json)
    + Body 

            {
                "message":"Your time start now",
                "data": { 
                    "id":197,
                    "title":"ABC1",
                    "description":{  
                        "html":"",
                        "content":""
                    },
                    "estimation":"0",
                    "start_at":{  
                        "date":null,
                        "time":null,
                        "datetime":null,
                        "timezone":"Etc\/UTC",
                        "timestamp":null
                    },
                    "due_date":{  
                        "date":null,
                        "time":null,
                        "datetime":null,
                        "timezone":"Etc\/UTC",
                        "timestamp":null
                    },
                    "complexity":"basic",
                    "priority":"medium",
                    "order":1,
                    "payable":"no",
                    "recurrent":"0",
                    "parent_id":"0",
                    "status":"incomplete",
                    "project_id":"7",
                    "category_id":null,
                    "created_at":{  
                        "date":"2019-07-03",
                        "time":"10:08:56",
                        "datetime":"2019-07-03 10:08:56",
                        "timezone":"Etc\/UTC",
                        "timestamp":"2019-07-03T10:08:56+00:00"
                    },
                    "completed_at":{  
                        "date":null,
                        "time":null,
                        "datetime":null,
                        "timezone":"Etc\/UTC",
                        "timestamp":null
                    },
                    "updated_at":{  
                        "date":"2019-08-21",
                        "time":"05:26:39",
                        "datetime":"2019-08-21 05:26:39",
                        "timezone":"Etc\/UTC",
                        "timestamp":"2019-08-21T05:26:39+00:00"
                    },
                    "task_list_id":176,
                    "meta":{  
                        "privacy":"1",
                        "total_comment":3,
                        "total_files":0,
                        "total_board":1,
                        "total_assignee":1,
                        "can_complete_task":true
                    },
                    "gantt_links":{  
                        "data":[  

                        ]
                    },
                    "new_sub_task_form":false,
                    "sub_tasks":[  

                    ],
                    "sub_task_content":false,
                    "time":{  
                        "data":[  
                            {  
                            "id":4,
                            "user_id":"1",
                            "project_id":"7",
                            "list_id":"176",
                            "task_id":"197",
                            "start":{  
                                "date":"2019-08-21",
                                "time":"05:27:29",
                                "datetime":"2019-08-21 05:27:29",
                                "timezone":"Etc\/UTC",
                                "timestamp":"2019-08-21T05:27:29+00:00"
                            },
                            "stop":{  
                                "date":null,
                                "time":null,
                                "datetime":null,
                                "timezone":"Etc\/UTC",
                                "timestamp":null
                            },
                            "total":{  
                                "hour":"00",
                                "minute":"00",
                                "second":"00",
                                "total_second":"0"
                            },
                            "run_status":"1",
                            "created_by":"1",
                            "updated_by":"1",
                            "updated_at":"2019-08-21T05:27:29.000000Z",
                            "created_at":{  
                                "date":"2019-08-21",
                                "time":"05:27:29",
                                "datetime":"2019-08-21 05:27:29",
                                "timezone":"Etc\/UTC",
                                "timestamp":"2019-08-21T05:27:29+00:00"
                            },
                            "user":{  
                                "data":{  
                                    "id":1,
                                    "username":"admin",
                                    "nicename":"admin",
                                    "email":"rrcucse.11@gmail.com",
                                    "profile_url":"",
                                    "display_name":"admin",
                                    "manage_capability":1,
                                    "create_capability":1,
                                    "avatar_url":"http:\/\/1.gravatar.com\/avatar\/41192594a3bd644bf17130a05a78a8f1?s=96&d=mm&r=g",
                                    "github":"rokibulfsdsdafrokib",
                                    "bitbucket":"rokibulisalmfsd",
                                    "roles":{  
                                        "data":[  
                                        {  
                                            "id":1,
                                            "title":"Manager",
                                            "description":"Manager is a person who manages the project.",
                                            "created_at":{  
                                                "date":"2019-05-21",
                                                "time":"05:36:21",
                                                "datetime":"2019-05-21 05:36:21",
                                                "timezone":"Etc\/UTC",
                                                "timestamp":"2019-05-21T05:36:21+00:00"
                                            },
                                            "slug":"manager"
                                        }
                                        ]
                                    }
                                }
                            }
                            }
                        ],
                        "meta":{  
                            "totalTime":{  
                            "hour":"00",
                            "minute":"00",
                            "second":"00",
                            "total_second":0
                            },
                            "totalTaskTime":{  
                            "hour":"00",
                            "minute":"00",
                            "second":"00",
                            "total_second":0
                            },
                            "running":true
                        }
                    },
                    "is_stop_watch_visible":true,
                    "custom_time_form":false,
                    "labels":{  
                        "data":[  

                        ]
                    },
                    "creator":{  
                        "data":{  
                            "id":1,
                            "username":"admin",
                            "nicename":"admin",
                            "email":"rrcucse.11@gmail.com",
                            "profile_url":"",
                            "display_name":"admin",
                            "manage_capability":1,
                            "create_capability":1,
                            "avatar_url":"http:\/\/1.gravatar.com\/avatar\/41192594a3bd644bf17130a05a78a8f1?s=96&d=mm&r=g",
                            "github":"rokibulfsdsdafrokib",
                            "bitbucket":"rokibulisalmfsd",
                            "roles":{  
                            "data":[  
                                {  
                                    "id":1,
                                    "title":"Manager",
                                    "description":"Manager is a person who manages the project.",
                                    "created_at":{  
                                        "date":"2019-05-21",
                                        "time":"05:36:21",
                                        "datetime":"2019-05-21 05:36:21",
                                        "timezone":"Etc\/UTC",
                                        "timestamp":"2019-05-21T05:36:21+00:00"
                                    },
                                    "slug":"manager"
                                }
                            ]
                            }
                        }
                    },
                    "updater":{  
                        "data":{  
                            "id":1,
                            "username":"admin",
                            "nicename":"admin",
                            "email":"rrcucse.11@gmail.com",
                            "profile_url":"",
                            "display_name":"admin",
                            "manage_capability":1,
                            "create_capability":1,
                            "avatar_url":"http:\/\/1.gravatar.com\/avatar\/41192594a3bd644bf17130a05a78a8f1?s=96&d=mm&r=g",
                            "github":"rokibulfsdsdafrokib",
                            "bitbucket":"rokibulisalmfsd",
                            "roles":{  
                            "data":[  
                                {  
                                    "id":1,
                                    "title":"Manager",
                                    "description":"Manager is a person who manages the project.",
                                    "created_at":{  
                                        "date":"2019-05-21",
                                        "time":"05:36:21",
                                        "datetime":"2019-05-21 05:36:21",
                                        "timezone":"Etc\/UTC",
                                        "timestamp":"2019-05-21T05:36:21+00:00"
                                    },
                                    "slug":"manager"
                                }
                            ]
                            }
                        }
                    },
                    "task_list":{  
                        "data":{  
                            "id":176,
                            "title":"clientlist",
                            "description":"",
                            "order":10000007,
                            "status":"current",
                            "created_at":{  
                            "date":"2019-07-03",
                            "time":"04:11:31",
                            "datetime":"2019-07-03 04:11:31",
                            "timezone":"Etc\/UTC",
                            "timestamp":"2019-07-03T04:11:31+00:00"
                            },
                            "meta":{  
                            "privacy":"1",
                            "total_tasks":2,
                            "total_complete_tasks":0,
                            "total_incomplete_tasks":2,
                            "total_comments":0,
                            "totla_files":0,
                            "total_assignees":0
                            },
                            "extra":true,
                            "project_id":"7",
                            "creator":{  
                            "data":{  
                                "id":3,
                                "username":"user_login2",
                                "nicename":"user_login2",
                                "email":"example2@example.com",
                                "profile_url":"",
                                "display_name":"user_login2",
                                "manage_capability":0,
                                "create_capability":0,
                                "avatar_url":"http:\/\/2.gravatar.com\/avatar\/b75a7dd26f16ae13b440190aef177ac1?s=96&d=mm&r=g",
                                "github":"mishu123",
                                "bitbucket":"mishu24",
                                "roles":{  
                                    "data":[  
                                        {  
                                        "id":1,
                                        "title":"Manager",
                                        "description":"Manager is a person who manages the project.",
                                        "created_at":{  
                                            "date":"2019-05-21",
                                            "time":"05:36:21",
                                            "datetime":"2019-05-21 05:36:21",
                                            "timezone":"Etc\/UTC",
                                            "timestamp":"2019-05-21T05:36:21+00:00"
                                        },
                                        "slug":"manager"
                                        },
                                        {  
                                        "id":3,
                                        "title":"Client",
                                        "description":"Client is a person who provid the project.",
                                        "created_at":{  
                                            "date":"2019-05-21",
                                            "time":"05:36:21",
                                            "datetime":"2019-05-21 05:36:21",
                                            "timezone":"Etc\/UTC",
                                            "timestamp":"2019-05-21T05:36:21+00:00"
                                        },
                                        "slug":"client"
                                        }
                                    ]
                                }
                            }
                            },
                            "updater":{  
                            "data":{  
                                "id":3,
                                "username":"user_login2",
                                "nicename":"user_login2",
                                "email":"example2@example.com",
                                "profile_url":"",
                                "display_name":"user_login2",
                                "manage_capability":0,
                                "create_capability":0,
                                "avatar_url":"http:\/\/2.gravatar.com\/avatar\/b75a7dd26f16ae13b440190aef177ac1?s=96&d=mm&r=g",
                                "github":"mishu123",
                                "bitbucket":"mishu24",
                                "roles":{  
                                    "data":[  
                                        {  
                                        "id":1,
                                        "title":"Manager",
                                        "description":"Manager is a person who manages the project.",
                                        "created_at":{  
                                            "date":"2019-05-21",
                                            "time":"05:36:21",
                                            "datetime":"2019-05-21 05:36:21",
                                            "timezone":"Etc\/UTC",
                                            "timestamp":"2019-05-21T05:36:21+00:00"
                                        },
                                        "slug":"manager"
                                        },
                                        {  
                                        "id":3,
                                        "title":"Client",
                                        "description":"Client is a person who provid the project.",
                                        "created_at":{  
                                            "date":"2019-05-21",
                                            "time":"05:36:21",
                                            "datetime":"2019-05-21 05:36:21",
                                            "timezone":"Etc\/UTC",
                                            "timestamp":"2019-05-21T05:36:21+00:00"
                                        },
                                        "slug":"client"
                                        }
                                    ]
                                }
                            }
                            }
                        }
                    },
                    "assignees":{  
                        "data":[  
                            {  
                            "id":1,
                            "username":"admin",
                            "nicename":"admin",
                            "email":"rrcucse.11@gmail.com",
                            "profile_url":"",
                            "display_name":"admin",
                            "manage_capability":1,
                            "create_capability":1,
                            "avatar_url":"http:\/\/1.gravatar.com\/avatar\/41192594a3bd644bf17130a05a78a8f1?s=96&d=mm&r=g",
                            "github":"rokibulfsdsdafrokib",
                            "bitbucket":"rokibulisalmfsd",
                            "completed_at":{  
                                "date":null,
                                "time":null,
                                "datetime":null,
                                "timezone":"Etc\/UTC",
                                "timestamp":null
                            },
                            "started_at":{  
                                "date":null,
                                "time":null,
                                "datetime":null,
                                "timezone":"Etc\/UTC",
                                "timestamp":null
                            },
                            "assigned_at":{  
                                "date":"2019-08-21",
                                "time":"05:26:39",
                                "datetime":"2019-08-21 05:26:39",
                                "timezone":"Etc\/UTC",
                                "timestamp":"2019-08-21T05:26:39+00:00"
                            },
                            "status":0,
                            "roles":{  
                                "data":[  
                                    {  
                                        "id":1,
                                        "title":"Manager",
                                        "description":"Manager is a person who manages the project.",
                                        "created_at":{  
                                        "date":"2019-05-21",
                                        "time":"05:36:21",
                                        "datetime":"2019-05-21 05:36:21",
                                        "timezone":"Etc\/UTC",
                                        "timestamp":"2019-05-21T05:36:21+00:00"
                                        },
                                        "slug":"manager"
                                    }
                                ]
                            }
                            }
                        ]
                    }
                 }
            }
## custom-time [/custom-time]
### custom-time [POST]

+ project_id (number,required)
+ list_id (number,required)
+ task_id (number,required)
+ start (date,required)
+ stop (time,required)

+ Request 
    + Body

            {
                "start": "2019-08-08",
                "stop": "05:00",
                "project_id": 7,
                "list_id": 168,
                "task_id": 207
            }

+ Response 200 (application/json)
    + Body 

            {
                "message":"Your time log update successfully",
                "data":{  
                    "id":193,
                    "title":"abc",
                    "description":{  
                        "html":"",
                        "content":null
                    },
                    "estimation":"0",
                    "start_at":{  
                        "date":null,
                        "time":null,
                        "datetime":null,
                        "timezone":"Etc\/UTC",
                        "timestamp":null
                    },
                    "due_date":{  
                        "date":null,
                        "time":null,
                        "datetime":null,
                        "timezone":"Etc\/UTC",
                        "timestamp":null
                    },
                    "complexity":"basic",
                    "priority":"medium",
                    "order":1,
                    "payable":"no",
                    "recurrent":"0",
                    "parent_id":"0",
                    "status":"incomplete",
                    "project_id":"7",
                    "category_id":null,
                    "created_at":{  
                        "date":"2019-07-01",
                        "time":"10:10:07",
                        "datetime":"2019-07-01 10:10:07",
                        "timezone":"Etc\/UTC",
                        "timestamp":"2019-07-01T10:10:07+00:00"
                    },
                    "completed_at":{  
                        "date":null,
                        "time":null,
                        "datetime":null,
                        "timezone":"Etc\/UTC",
                        "timestamp":null
                    },
                    "updated_at":{  
                        "date":"2019-07-01",
                        "time":"10:10:07",
                        "datetime":"2019-07-01 10:10:07",
                        "timezone":"Etc\/UTC",
                        "timestamp":"2019-07-01T10:10:07+00:00"
                    },
                    "task_list_id":171,
                    "meta":{  
                        "total_comment":0,
                        "total_files":0,
                        "total_board":1,
                        "total_assignee":1,
                        "can_complete_task":true
                    },
                    "gantt_links":{  
                        "data":[  

                        ]
                    },
                    "new_sub_task_form":false,
                    "sub_tasks":[  

                    ],
                    "sub_task_content":false,
                    "time":{  
                        "data":[  
                            {  
                            "id":5,
                            "user_id":"1",
                            "project_id":"7",
                            "list_id":"171",
                            "task_id":"193",
                            "start":{  
                                "date":"2019-08-21",
                                "time":"00:00:00",
                                "datetime":"2019-08-21 00:00:00",
                                "timezone":"Etc\/UTC",
                                "timestamp":"2019-08-21T00:00:00+00:00"
                            },
                            "stop":{  
                                "date":"2019-08-21",
                                "time":"00:00:00",
                                "datetime":"2019-08-21 00:00:00",
                                "timezone":"Etc\/UTC",
                                "timestamp":"2019-08-21T00:00:00+00:00"
                            },
                            "total":{  
                                "hour":"05",
                                "minute":"30",
                                "second":"00",
                                "total_second":"19800"
                            },
                            "run_status":"0",
                            "created_by":"1",
                            "updated_by":"1",
                            "updated_at":"2019-08-21T05:43:55.000000Z",
                            "created_at":{  
                                "date":"2019-08-21",
                                "time":"05:43:55",
                                "datetime":"2019-08-21 05:43:55",
                                "timezone":"Etc\/UTC",
                                "timestamp":"2019-08-21T05:43:55+00:00"
                            },
                            "user":{  
                                "data":{  
                                    "id":1,
                                    "username":"admin",
                                    "nicename":"admin",
                                    "email":"rrcucse.11@gmail.com",
                                    "profile_url":"",
                                    "display_name":"admin",
                                    "manage_capability":1,
                                    "create_capability":1,
                                    "avatar_url":"http:\/\/1.gravatar.com\/avatar\/41192594a3bd644bf17130a05a78a8f1?s=96&d=mm&r=g",
                                    "github":"rokibulfsdsdafrokib",
                                    "bitbucket":"rokibulisalmfsd",
                                    "roles":{  
                                        "data":[  
                                        {  
                                            "id":1,
                                            "title":"Manager",
                                            "description":"Manager is a person who manages the project.",
                                            "created_at":{  
                                                "date":"2019-05-21",
                                                "time":"05:36:21",
                                                "datetime":"2019-05-21 05:36:21",
                                                "timezone":"Etc\/UTC",
                                                "timestamp":"2019-05-21T05:36:21+00:00"
                                            },
                                            "slug":"manager"
                                        }
                                        ]
                                    }
                                }
                            }
                            }
                        ],
                        "meta":{  
                            "totalTime":{  
                            "hour":"05",
                            "minute":"30",
                            "second":"00",
                            "total_second":19800
                            },
                            "totalTaskTime":{  
                            "hour":"05",
                            "minute":"30",
                            "second":"00",
                            "total_second":"19800"
                            },
                            "running":false
                        }
                    },
                    "is_stop_watch_visible":false,
                    "custom_time_form":false,
                    "labels":{  
                        "data":[  

                        ]
                    },
                    "creator":{  
                        "data":{  
                            "id":1,
                            "username":"admin",
                            "nicename":"admin",
                            "email":"rrcucse.11@gmail.com",
                            "profile_url":"",
                            "display_name":"admin",
                            "manage_capability":1,
                            "create_capability":1,
                            "avatar_url":"http:\/\/1.gravatar.com\/avatar\/41192594a3bd644bf17130a05a78a8f1?s=96&d=mm&r=g",
                            "github":"rokibulfsdsdafrokib",
                            "bitbucket":"rokibulisalmfsd",
                            "roles":{  
                            "data":[  
                                {  
                                    "id":1,
                                    "title":"Manager",
                                    "description":"Manager is a person who manages the project.",
                                    "created_at":{  
                                        "date":"2019-05-21",
                                        "time":"05:36:21",
                                        "datetime":"2019-05-21 05:36:21",
                                        "timezone":"Etc\/UTC",
                                        "timestamp":"2019-05-21T05:36:21+00:00"
                                    },
                                    "slug":"manager"
                                }
                            ]
                            }
                        }
                    },
                    "updater":{  
                        "data":{  
                            "id":1,
                            "username":"admin",
                            "nicename":"admin",
                            "email":"rrcucse.11@gmail.com",
                            "profile_url":"",
                            "display_name":"admin",
                            "manage_capability":1,
                            "create_capability":1,
                            "avatar_url":"http:\/\/1.gravatar.com\/avatar\/41192594a3bd644bf17130a05a78a8f1?s=96&d=mm&r=g",
                            "github":"rokibulfsdsdafrokib",
                            "bitbucket":"rokibulisalmfsd",
                            "roles":{  
                            "data":[  
                                {  
                                    "id":1,
                                    "title":"Manager",
                                    "description":"Manager is a person who manages the project.",
                                    "created_at":{  
                                        "date":"2019-05-21",
                                        "time":"05:36:21",
                                        "datetime":"2019-05-21 05:36:21",
                                        "timezone":"Etc\/UTC",
                                        "timestamp":"2019-05-21T05:36:21+00:00"
                                    },
                                    "slug":"manager"
                                }
                            ]
                            }
                        }
                    },
                    "task_list":{  
                        "data":{  
                            "id":171,
                            "title":"testlist",
                            "description":"",
                            "order":10000005,
                            "status":"current",
                            "created_at":{  
                            "date":"2019-07-01",
                            "time":"10:09:57",
                            "datetime":"2019-07-01 10:09:57",
                            "timezone":"Etc\/UTC",
                            "timestamp":"2019-07-01T10:09:57+00:00"
                            },
                            "meta":{  
                            "privacy":"0",
                            "total_tasks":2,
                            "total_complete_tasks":0,
                            "total_incomplete_tasks":2,
                            "total_comments":0,
                            "totla_files":0,
                            "total_assignees":0
                            },
                            "extra":true,
                            "project_id":"7",
                            "creator":{  
                            "data":{  
                                "id":1,
                                "username":"admin",
                                "nicename":"admin",
                                "email":"rrcucse.11@gmail.com",
                                "profile_url":"",
                                "display_name":"admin",
                                "manage_capability":1,
                                "create_capability":1,
                                "avatar_url":"http:\/\/1.gravatar.com\/avatar\/41192594a3bd644bf17130a05a78a8f1?s=96&d=mm&r=g",
                                "github":"rokibulfsdsdafrokib",
                                "bitbucket":"rokibulisalmfsd",
                                "roles":{  
                                    "data":[  
                                        {  
                                        "id":1,
                                        "title":"Manager",
                                        "description":"Manager is a person who manages the project.",
                                        "created_at":{  
                                            "date":"2019-05-21",
                                            "time":"05:36:21",
                                            "datetime":"2019-05-21 05:36:21",
                                            "timezone":"Etc\/UTC",
                                            "timestamp":"2019-05-21T05:36:21+00:00"
                                        },
                                        "slug":"manager"
                                        }
                                    ]
                                }
                            }
                            },
                            "updater":{  
                            "data":{  
                                "id":1,
                                "username":"admin",
                                "nicename":"admin",
                                "email":"rrcucse.11@gmail.com",
                                "profile_url":"",
                                "display_name":"admin",
                                "manage_capability":1,
                                "create_capability":1,
                                "avatar_url":"http:\/\/1.gravatar.com\/avatar\/41192594a3bd644bf17130a05a78a8f1?s=96&d=mm&r=g",
                                "github":"rokibulfsdsdafrokib",
                                "bitbucket":"rokibulisalmfsd",
                                "roles":{  
                                    "data":[  
                                        {  
                                        "id":1,
                                        "title":"Manager",
                                        "description":"Manager is a person who manages the project.",
                                        "created_at":{  
                                            "date":"2019-05-21",
                                            "time":"05:36:21",
                                            "datetime":"2019-05-21 05:36:21",
                                            "timezone":"Etc\/UTC",
                                            "timestamp":"2019-05-21T05:36:21+00:00"
                                        },
                                        "slug":"manager"
                                        }
                                    ]
                                }
                            }
                            }
                        }
                    },
                    "assignees":{  
                        "data":[  
                            {  
                            "id":1,
                            "username":"admin",
                            "nicename":"admin",
                            "email":"rrcucse.11@gmail.com",
                            "profile_url":"",
                            "display_name":"admin",
                            "manage_capability":1,
                            "create_capability":1,
                            "avatar_url":"http:\/\/1.gravatar.com\/avatar\/41192594a3bd644bf17130a05a78a8f1?s=96&d=mm&r=g",
                            "github":"rokibulfsdsdafrokib",
                            "bitbucket":"rokibulisalmfsd",
                            "completed_at":{  
                                "date":null,
                                "time":null,
                                "datetime":null,
                                "timezone":"Etc\/UTC",
                                "timestamp":null
                            },
                            "started_at":{  
                                "date":null,
                                "time":null,
                                "datetime":null,
                                "timezone":"Etc\/UTC",
                                "timestamp":null
                            },
                            "assigned_at":{  
                                "date":"2019-07-01",
                                "time":"10:10:07",
                                "datetime":"2019-07-01 10:10:07",
                                "timezone":"Etc\/UTC",
                                "timestamp":"2019-07-01T10:10:07+00:00"
                            },
                            "status":0,
                            "roles":{  
                                "data":[  
                                    {  
                                        "id":1,
                                        "title":"Manager",
                                        "description":"Manager is a person who manages the project.",
                                        "created_at":{  
                                        "date":"2019-05-21",
                                        "time":"05:36:21",
                                        "datetime":"2019-05-21 05:36:21",
                                        "timezone":"Etc\/UTC",
                                        "timestamp":"2019-05-21T05:36:21+00:00"
                                        },
                                        "slug":"manager"
                                    }
                                ]
                            }
                            }
                        ]
                    }
                }
            }

## timeStop [/time/update]

### Stop Time [POST]

+ project_id (number,required)
+ list_id (number,required)
+ task_id (number,required)

+ Request 
    + Body

            {       
                "project_id": 7,
                "list_id": 168,
                "task_id": 207
            }

+ Response 200 (application/json)
    + Body 

            {
                {  
                    "message":"Your time start now",
                    "data":{  
                        "id":197,
                        "title":"ABC1",
                        "description":{  
                            "html":"",
                            "content":""
                        },
                        "estimation":"0",
                        "start_at":{  
                            "date":null,
                            "time":null,
                            "datetime":null,
                            "timezone":"Etc\/UTC",
                            "timestamp":null
                        },
                        "due_date":{  
                            "date":null,
                            "time":null,
                            "datetime":null,
                            "timezone":"Etc\/UTC",
                            "timestamp":null
                        },
                        "complexity":"basic",
                        "priority":"medium",
                        "order":1,
                        "payable":"no",
                        "recurrent":"0",
                        "parent_id":"0",
                        "status":"incomplete",
                        "project_id":"7",
                        "category_id":null,
                        "created_at":{  
                            "date":"2019-07-03",
                            "time":"10:08:56",
                            "datetime":"2019-07-03 10:08:56",
                            "timezone":"Etc\/UTC",
                            "timestamp":"2019-07-03T10:08:56+00:00"
                        },
                        "completed_at":{  
                            "date":null,
                            "time":null,
                            "datetime":null,
                            "timezone":"Etc\/UTC",
                            "timestamp":null
                        },
                        "updated_at":{  
                            "date":"2019-08-21",
                            "time":"05:26:39",
                            "datetime":"2019-08-21 05:26:39",
                            "timezone":"Etc\/UTC",
                            "timestamp":"2019-08-21T05:26:39+00:00"
                        },
                        "task_list_id":176,
                        "meta":{  
                            "privacy":"1",
                            "total_comment":3,
                            "total_files":0,
                            "total_board":1,
                            "total_assignee":1,
                            "can_complete_task":true
                        },
                        "gantt_links":{  
                            "data":[  

                            ]
                        },
                        "new_sub_task_form":false,
                        "sub_tasks":[  

                        ],
                        "sub_task_content":false,
                        "time":{  
                            "data":[  
                                {  
                                "id":4,
                                "user_id":"1",
                                "project_id":"7",
                                "list_id":"176",
                                "task_id":"197",
                                "start":{  
                                    "date":"2019-08-21",
                                    "time":"05:27:29",
                                    "datetime":"2019-08-21 05:27:29",
                                    "timezone":"Etc\/UTC",
                                    "timestamp":"2019-08-21T05:27:29+00:00"
                                },
                                "stop":{  
                                    "date":null,
                                    "time":null,
                                    "datetime":null,
                                    "timezone":"Etc\/UTC",
                                    "timestamp":null
                                },
                                "total":{  
                                    "hour":"00",
                                    "minute":"00",
                                    "second":"00",
                                    "total_second":"0"
                                },
                                "run_status":"1",
                                "created_by":"1",
                                "updated_by":"1",
                                "updated_at":"2019-08-21T05:27:29.000000Z",
                                "created_at":{  
                                    "date":"2019-08-21",
                                    "time":"05:27:29",
                                    "datetime":"2019-08-21 05:27:29",
                                    "timezone":"Etc\/UTC",
                                    "timestamp":"2019-08-21T05:27:29+00:00"
                                },
                                "user":{  
                                    "data":{  
                                        "id":1,
                                        "username":"admin",
                                        "nicename":"admin",
                                        "email":"rrcucse.11@gmail.com",
                                        "profile_url":"",
                                        "display_name":"admin",
                                        "manage_capability":1,
                                        "create_capability":1,
                                        "avatar_url":"http:\/\/1.gravatar.com\/avatar\/41192594a3bd644bf17130a05a78a8f1?s=96&d=mm&r=g",
                                        "github":"rokibulfsdsdafrokib",
                                        "bitbucket":"rokibulisalmfsd",
                                        "roles":{  
                                            "data":[  
                                            {  
                                                "id":1,
                                                "title":"Manager",
                                                "description":"Manager is a person who manages the project.",
                                                "created_at":{  
                                                    "date":"2019-05-21",
                                                    "time":"05:36:21",
                                                    "datetime":"2019-05-21 05:36:21",
                                                    "timezone":"Etc\/UTC",
                                                    "timestamp":"2019-05-21T05:36:21+00:00"
                                                },
                                                "slug":"manager"
                                            }
                                            ]
                                        }
                                    }
                                }
                                }
                            ],
                            "meta":{  
                                "totalTime":{  
                                "hour":"00",
                                "minute":"00",
                                "second":"00",
                                "total_second":0
                                },
                                "totalTaskTime":{  
                                "hour":"00",
                                "minute":"00",
                                "second":"00",
                                "total_second":0
                                },
                                "running":true
                            }
                        },
                        "is_stop_watch_visible":true,
                        "custom_time_form":false,
                        "labels":{  
                            "data":[  

                            ]
                        },
                        "creator":{  
                            "data":{  
                                "id":1,
                                "username":"admin",
                                "nicename":"admin",
                                "email":"rrcucse.11@gmail.com",
                                "profile_url":"",
                                "display_name":"admin",
                                "manage_capability":1,
                                "create_capability":1,
                                "avatar_url":"http:\/\/1.gravatar.com\/avatar\/41192594a3bd644bf17130a05a78a8f1?s=96&d=mm&r=g",
                                "github":"rokibulfsdsdafrokib",
                                "bitbucket":"rokibulisalmfsd",
                                "roles":{  
                                "data":[  
                                    {  
                                        "id":1,
                                        "title":"Manager",
                                        "description":"Manager is a person who manages the project.",
                                        "created_at":{  
                                            "date":"2019-05-21",
                                            "time":"05:36:21",
                                            "datetime":"2019-05-21 05:36:21",
                                            "timezone":"Etc\/UTC",
                                            "timestamp":"2019-05-21T05:36:21+00:00"
                                        },
                                        "slug":"manager"
                                    }
                                ]
                                }
                            }
                        },
                        "updater":{  
                            "data":{  
                                "id":1,
                                "username":"admin",
                                "nicename":"admin",
                                "email":"rrcucse.11@gmail.com",
                                "profile_url":"",
                                "display_name":"admin",
                                "manage_capability":1,
                                "create_capability":1,
                                "avatar_url":"http:\/\/1.gravatar.com\/avatar\/41192594a3bd644bf17130a05a78a8f1?s=96&d=mm&r=g",
                                "github":"rokibulfsdsdafrokib",
                                "bitbucket":"rokibulisalmfsd",
                                "roles":{  
                                "data":[  
                                    {  
                                        "id":1,
                                        "title":"Manager",
                                        "description":"Manager is a person who manages the project.",
                                        "created_at":{  
                                            "date":"2019-05-21",
                                            "time":"05:36:21",
                                            "datetime":"2019-05-21 05:36:21",
                                            "timezone":"Etc\/UTC",
                                            "timestamp":"2019-05-21T05:36:21+00:00"
                                        },
                                        "slug":"manager"
                                    }
                                ]
                                }
                            }
                        },
                        "task_list":{  
                            "data":{  
                                "id":176,
                                "title":"clientlist",
                                "description":"",
                                "order":10000007,
                                "status":"current",
                                "created_at":{  
                                "date":"2019-07-03",
                                "time":"04:11:31",
                                "datetime":"2019-07-03 04:11:31",
                                "timezone":"Etc\/UTC",
                                "timestamp":"2019-07-03T04:11:31+00:00"
                                },
                                "meta":{  
                                "privacy":"1",
                                "total_tasks":2,
                                "total_complete_tasks":0,
                                "total_incomplete_tasks":2,
                                "total_comments":0,
                                "totla_files":0,
                                "total_assignees":0
                                },
                                "extra":true,
                                "project_id":"7",
                                "creator":{  
                                "data":{  
                                    "id":3,
                                    "username":"user_login2",
                                    "nicename":"user_login2",
                                    "email":"example2@example.com",
                                    "profile_url":"",
                                    "display_name":"user_login2",
                                    "manage_capability":0,
                                    "create_capability":0,
                                    "avatar_url":"http:\/\/2.gravatar.com\/avatar\/b75a7dd26f16ae13b440190aef177ac1?s=96&d=mm&r=g",
                                    "github":"mishu123",
                                    "bitbucket":"mishu24",
                                    "roles":{  
                                        "data":[  
                                            {  
                                            "id":1,
                                            "title":"Manager",
                                            "description":"Manager is a person who manages the project.",
                                            "created_at":{  
                                                "date":"2019-05-21",
                                                "time":"05:36:21",
                                                "datetime":"2019-05-21 05:36:21",
                                                "timezone":"Etc\/UTC",
                                                "timestamp":"2019-05-21T05:36:21+00:00"
                                            },
                                            "slug":"manager"
                                            },
                                            {  
                                            "id":3,
                                            "title":"Client",
                                            "description":"Client is a person who provid the project.",
                                            "created_at":{  
                                                "date":"2019-05-21",
                                                "time":"05:36:21",
                                                "datetime":"2019-05-21 05:36:21",
                                                "timezone":"Etc\/UTC",
                                                "timestamp":"2019-05-21T05:36:21+00:00"
                                            },
                                            "slug":"client"
                                            }
                                        ]
                                    }
                                }
                                },
                                "updater":{  
                                "data":{  
                                    "id":3,
                                    "username":"user_login2",
                                    "nicename":"user_login2",
                                    "email":"example2@example.com",
                                    "profile_url":"",
                                    "display_name":"user_login2",
                                    "manage_capability":0,
                                    "create_capability":0,
                                    "avatar_url":"http:\/\/2.gravatar.com\/avatar\/b75a7dd26f16ae13b440190aef177ac1?s=96&d=mm&r=g",
                                    "github":"mishu123",
                                    "bitbucket":"mishu24",
                                    "roles":{  
                                        "data":[  
                                            {  
                                            "id":1,
                                            "title":"Manager",
                                            "description":"Manager is a person who manages the project.",
                                            "created_at":{  
                                                "date":"2019-05-21",
                                                "time":"05:36:21",
                                                "datetime":"2019-05-21 05:36:21",
                                                "timezone":"Etc\/UTC",
                                                "timestamp":"2019-05-21T05:36:21+00:00"
                                            },
                                            "slug":"manager"
                                            },
                                            {  
                                            "id":3,
                                            "title":"Client",
                                            "description":"Client is a person who provid the project.",
                                            "created_at":{  
                                                "date":"2019-05-21",
                                                "time":"05:36:21",
                                                "datetime":"2019-05-21 05:36:21",
                                                "timezone":"Etc\/UTC",
                                                "timestamp":"2019-05-21T05:36:21+00:00"
                                            },
                                            "slug":"client"
                                            }
                                        ]
                                    }
                                }
                                }
                            }
                        },
                        "assignees":{  
                            "data":[  
                                {  
                                "id":1,
                                "username":"admin",
                                "nicename":"admin",
                                "email":"rrcucse.11@gmail.com",
                                "profile_url":"",
                                "display_name":"admin",
                                "manage_capability":1,
                                "create_capability":1,
                                "avatar_url":"http:\/\/1.gravatar.com\/avatar\/41192594a3bd644bf17130a05a78a8f1?s=96&d=mm&r=g",
                                "github":"rokibulfsdsdafrokib",
                                "bitbucket":"rokibulisalmfsd",
                                "completed_at":{  
                                    "date":null,
                                    "time":null,
                                    "datetime":null,
                                    "timezone":"Etc\/UTC",
                                    "timestamp":null
                                },
                                "started_at":{  
                                    "date":null,
                                    "time":null,
                                    "datetime":null,
                                    "timezone":"Etc\/UTC",
                                    "timestamp":null
                                },
                                "assigned_at":{  
                                    "date":"2019-08-21",
                                    "time":"05:26:39",
                                    "datetime":"2019-08-21 05:26:39",
                                    "timezone":"Etc\/UTC",
                                    "timestamp":"2019-08-21T05:26:39+00:00"
                                },
                                "status":0,
                                "roles":{  
                                    "data":[  
                                        {  
                                            "id":1,
                                            "title":"Manager",
                                            "description":"Manager is a person who manages the project.",
                                            "created_at":{  
                                            "date":"2019-05-21",
                                            "time":"05:36:21",
                                            "datetime":"2019-05-21 05:36:21",
                                            "timezone":"Etc\/UTC",
                                            "timestamp":"2019-05-21T05:36:21+00:00"
                                            },
                                            "slug":"manager"
                                        }
                                    ]
                                }
                                }
                            ]
                        }
                    }
                }
            }

## timedelete [/time/{time_id}/delete]

### delete Time [POST]


+ task_id (number,required) - Task id
+ list_id (number,required) - Task List Id

+ Parameters
    + time_id (number,required ) - Time Id

+ Request
    + Body
    
            {
                "task_id": 193,
                "list_id": 171,
            }

+ Response 200 (application/json)
    + Body 

            {
                "message":"Time log deleted successfully",
            }
