# Group User

## User OverDue Task csv [/users/{user_id}/advance-report/overdue-tasks/csv/{?project_id,start_date,due_date,user_id}]

### List All User-Overdue-Task csv [GET]
Fetches all  User Overdue Task in Csv

+ parameters
    + user_id    (number,required) - Id of User
    + project_id (number,optional) - Id of Project
    + start_date (date,optional) - Task start Date
    + due_date   (date,optional) - Task end Date

+ Response 200 (application/json)
    + Body
            
            {

            }

## User OverDue Task PDF [/users/{user_id}/advance-report/overdue-tasks/overdue-tasks-PDF/{?project_id,start_date,due_date,user_id}]

### List All User-Overdue-Task on PDF [GET]
Fetches all  User Overdue Task in PDF

+ parameters
    + user_id    (number,required) - Id of User
    + project_id (number,optional) - Id of Project
    + start_date (date,optional) - Task start Date
    + due_date   (date,optional) - Task end Date

+ Response 200 (application/json)
    + Body

            {
                
            }


## User Activites Task csv [/users/{user_id}/advance-report/user-activities/csv/{?project_id,start_date,due_date,user_id}]

### List All User-Activites csv [GET]
Fetches all  User Activites  in Csv

+ parameters
    + user_id    (number,required) - Id of User
    + project_id (number,optional) - Id of Project
    + start_date (date,optional) - Task start Date
    + due_date   (date,optional) - Task end Date

+ Response 200 (application/json)
    + Body
            
            {

            }


## User Activites  PDF [/users/{user_id}/advance-report/user-activities/pdf/{?project_id,start_date,due_date,user_id}]

### List All User-Activites on PDF [GET]
Fetches all  User Activites  in PDF

+ parameters
    + user_id    (number,required) - Id of User
    + project_id (number,optional) - Id of Project
    + start_date (date,optional) - Task start Date
    + due_date   (date,optional) - Task end Date

+ Response 200 (application/json)
    + Body

            {
                
            }

## User Completed Task csv [/users/{user_id}/advance-report/completed-tasks/csv/{?project_id,start_date,due_date,user_id}]

### List All User-completed Task csv [GET]
Fetches all  User completed Task  in Csv

+ parameters
    + user_id    (number,required) - Id of User
    + project_id (number,optional) - Id of Project
    + start_date (date,optional) - Task start Date
    + due_date   (date,optional) - Task end Date

+ Response 200 (application/json)
    + Body
            
            {

            }


## User completed Task  PDF [/users/{user_id}/advance-report/completed-tasks/pdf/{?project_id,start_date,due_date,user_id}]

### List All User-completed Task on PDF [GET]
Fetches all  User completed Task in PDF

+ parameters
    + user_id    (number,required) - Id of User
    + project_id (number,optional) - Id of Project
    + start_date (date,optional) - Task start Date
    + due_date   (date,optional) - Task end Date

+ Response 200 (application/json)
    + Body

            {
                
            }


## User unassigned Task csv [/users/{user_id}/advance-report/unassigned/csv/{?project_id,start_date,due_date,user_id}]

### List All User-unassigned Task csv [GET]
Fetches all  User unassigned Task  in Csv

+ parameters
    + user_id    (number,required) - Id of User
    + project_id (number,optional) - Id of Project
    + start_date (date,optional) - Task start Date
    + due_date   (date,optional) - Task end Date

+ Response 200 (application/json)
    + Body
            
            {

            }


## User unassigned Task  PDF [/users/{user_id}/advance-report/unassigned/pdf/{?project_id,start_date,due_date,user_id}]

### List All User-unassigned Task on PDF [GET]
Fetches all  User unassigned Task in PDF

+ parameters
    + user_id    (number,required) - Id of User
    + project_id (number,optional) - Id of Project
    + start_date (date,optional) - Task start Date
    + due_date   (date,optional) - Task end Date

+ Response 200 (application/json)
    + Body

            {
                
            }

## User millestone csv [/users/{user_id}/advance-report/milestone/csv/{?project_id,start_date,due_date,user_id}]

### List All User-millestone Task csv [GET]
Fetches all  User unassigned Task  in Csv

+ parameters
    + user_id    (number,required) - Id of User
    + project_id (number,optional) - Id of Project
    + start_date (date,optional) - Task start Date
    + due_date   (date,optional) - Task end Date

+ Response 200 (application/json)
    + Body
            
            {

            }

## User millestone Task  PDF [/users/{user_id}/advance-report/millestone/pdf/{?project_id,start_date,due_date,user_id}]

### List All User-millestone Task on PDF [GET]
Fetches all  User unassigned Task in PDF

+ parameters
    + user_id    (number,required) - Id of User
    + project_id (number,optional) - Id of Project
    + start_date (date,optional) - Task start Date
    + due_date   (date,optional) - Task end Date

+ Response 200 (application/json)
    + Body

            {
                
            }